<a href="https://colab.research.google.com/github/tojotk/ict_assesment/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# NLP - Natural Language Processing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (8.0.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 36.1 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

# Libraries

In [ ]:
import numpy as np
import pandas as pd
import string
import nltk

from nltk.stem import PorterStemmer , WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import AdaBoostClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

import gensim.downloader as api
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
from gensim.models import Word2Vec # Import the Word2Vec class

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

# Read Dataset

In [ ]:
filepath = '/content/drive/MyDrive/AI ML Course/Data/spam.xlsx'
df_spam = pd.read_excel(filepath)
df_spam

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will �_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

# EDA

In [ ]:
df_spam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [ ]:
# relevant data present only in first 2 columns
df_spam = df_spam[['v1', 'v2']]
df_spam.head(3)

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...

In [ ]:
# check unique values count
df_spam['v1'].value_counts()

v1
ham     4825
spam     747
Name: count, dtype: int64

# Preprocessing

## Punctuations

In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
sample_text = "Hello! Can we test #1 ($50.99) item? Yes, @John_Doe said: 'It's a well-known state-of-the-art 50% / 100% match [id: #789]—or is it?' Check example.com {file: data.csv, status: active | pending} <ok?> ~all done^;"

In [ ]:
sample_text

"Hello! Can we test #1 ($50.99) item? Yes, @John_Doe said: 'It's a well-known state-of-the-art 50% / 100% match [id: #789]—or is it?' Check example.com {file: data.csv, status: active | pending} <ok?> ~all done^;"

In [ ]:
def remove_punctuation(text):
  punctuationless_text =''.join([i for i in text if i not in string.punctuation])
  # comparing each character in 'text' against the punctuation list
  return punctuationless_text

In [ ]:
print('before')
print('************************************')
print(sample_text)
print('\n,\n')
print('after')
print('************************************')
print(remove_punctuation(sample_text))

before
************************************
Hello! Can we test #1 ($50.99) item? Yes, @John_Doe said: 'It's a well-known state-of-the-art 50% / 100% match [id: #789]—or is it?' Check example.com {file: data.csv, status: active | pending} <ok?> ~all done^;

,

after
************************************
Hello Can we test 1 5099 item Yes JohnDoe said Its a wellknown stateoftheart 50  100 match id 789—or is it Check examplecom file datacsv status active  pending ok all done

## Lowercasing

In [ ]:
punctuation_free_text = remove_punctuation(sample_text)

lower_case_text = punctuation_free_text.lower()
print('before')
print('************************************')
print(punctuation_free_text)
print('\n,\n')
print('after')
print('************************************')
print(lower_case_text)

before
************************************
Hello Can we test 1 5099 item Yes JohnDoe said Its a wellknown stateoftheart 50  100 match id 789—or is it Check examplecom file datacsv status active  pending ok all done

,

after
************************************
hello can we test 1 5099 item yes johndoe said its a wellknown stateoftheart 50  100 match id 789—or is it check examplecom file datacsv status active  pending ok all done

## Tokenaziation

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
# we convert the entire text into a list of unique words
# function to get tokens from the sentence
# input should be a text after punctuation removed and in lowercase
def tokenization(text):
    words_list = nltk.word_tokenize(text)
    return words_list

In [ ]:
tokens = tokenization(lower_case_text)
tokens

['hello',
 'can',
 'we',
 'test',
 '1',
 '5099',
 'item',
 'yes',
 'johndoe',
 'said',
 'its',
 'a',
 'wellknown',
 'stateoftheart',
 '50',
 '100',
 'match',
 'id',
 '789—or',
 'is',
 'it',
 'check',
 'examplecom',
 'file',
 'datacsv',
 'status',
 'active',
 'pending',
 'ok',
 'all',
 'done']

## STop words removal

In [ ]:
nltk.download('stopwords')
# get all the identified words in english
stop_words_list = nltk.corpus.stopwords.words('english')
stop_words_list

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
def stop_remove(tokens_list_arg):
  stop_word_removed_text = [i for i in tokens_list_arg if i not in stop_words_list]
  return stop_word_removed_text

In [ ]:
print('before')
print('**********')
print('count of tokens =', len(tokens))
print('/n/n')
print('after')
clean_tokens = stop_remove(tokens)
print('count of tokens = ',  len(clean_tokens))
print('**********')
print(clean_tokens)

before
**********
count of tokens = 31
/n/n
after
count of tokens =  24
**********
['hello', 'test', '1', '5099', 'item', 'yes', 'johndoe', 'said', 'wellknown', 'stateoftheart', '50', '100', 'match', 'id', '789—or', 'check', 'examplecom', 'file', 'datacsv', 'status', 'active', 'pending', 'ok', 'done']

## Stemming

In [ ]:
stem_obj = PorterStemmer()
def stemming(clean_tokens_arg):
  stem_list = [stem_obj.stem(word) for word in clean_tokens_arg ]
  return stem_list

In [ ]:
filtered_tokens = stop_remove(tokens)
stem_list = stemming(filtered_tokens)
print(filtered_tokens)
print(len(filtered_tokens))

print(stem_list)
print(len(stem_list))

['hello', 'test', '1', '5099', 'item', 'yes', 'johndoe', 'said', 'wellknown', 'stateoftheart', '50', '100', 'match', 'id', '789—or', 'check', 'examplecom', 'file', 'datacsv', 'status', 'active', 'pending', 'ok', 'done']
24
['hello', 'test', '1', '5099', 'item', 'ye', 'johndo', 'said', 'wellknown', 'stateoftheart', '50', '100', 'match', 'id', '789—or', 'check', 'examplecom', 'file', 'datacsv', 'statu', 'activ', 'pend', 'ok', 'done']
24

## Lemmatization

In [ ]:
lema_obj = WordNetLemmatizer()
def lemmatization(stem_token_list_arg):
  lemma_list = [lema_obj.lemmatize(word) for word in stem_token_list_arg]
  return lemma_list

In [ ]:
nltk.download('wordnet')
lemma_list = lemmatization(stem_list)
print(lemma_list)
print(len(lemma_list))

[nltk_data] Downloading package wordnet to /root/nltk_data...

['hello', 'test', '1', '5099', 'item', 'ye', 'johndo', 'said', 'wellknown', 'stateoftheart', '50', '100', 'match', 'id', '789—or', 'check', 'examplecom', 'file', 'datacsv', 'statu', 'activ', 'pend', 'ok', 'done']
24

### Applying Preprocessing to DataFrame

In [ ]:
df_spam['v2'] = df_spam['v2'].astype(str)

# Punctuation Removal
punctuationless_texts = []
for text in df_spam['v2']:
    punctuationless_texts.append(remove_punctuation(text))
df_spam['punctuationless_text'] = punctuationless_texts

# Lowercasing
lowercase_texts = []
for text in df_spam['punctuationless_text']:
    lowercase_texts.append(text.lower())
df_spam['lowercase_text'] = lowercase_texts

# Tokenization
tokenized_texts = []
for text in df_spam['lowercase_text']:
    tokenized_texts.append(tokenization(text))
df_spam['tokens'] = tokenized_texts

# Stopword Removal
stopwords_removed_lists = []
for token_list in df_spam['tokens']:
    stopwords_removed_lists.append(stop_remove(token_list))
df_spam['removed_stopwords'] = stopwords_removed_lists

# Stemming
stemmed_token_lists = []
for token_list in df_spam['removed_stopwords']:
    stemmed_token_lists.append(stemming(token_list))
df_spam['stemmed_tokens'] = stemmed_token_lists

# Lemmatization
lemmatized_token_lists = []
for token_list in df_spam['stemmed_tokens']:
    lemmatized_token_lists.append(lemmatization(token_list))
df_spam['lemmatized_tokens'] = lemmatized_token_lists

display(df_spam.head())

/tmp/ipykernel_1558/2675383456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_spam['v2'] = df_spam['v2'].astype(str)
/tmp/ipykernel_1558/2675383456.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_spam['punctuationless_text'] = punctuationless_texts
/tmp/ipykernel_1558/2675383456.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_spam['lowercase_text'] = lowercase_texts

,v1,v2,punctuationless_text,lowercase_text,tokens,removed_stopwords,stemmed_tokens,lemmatized_tokens
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go until jurong point crazy available only in ...,"[go, until, jurong, point, crazy, available, o...","[go, jurong, point, crazy, available, bugis, n...","[go, jurong, point, crazi, avail, bugi, n, gre...","[go, jurong, point, crazi, avail, bugi, n, gre..."
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni,"[ok, lar, joking, wif, u, oni]","[ok, lar, joking, wif, u, oni]","[ok, lar, joke, wif, u, oni]","[ok, lar, joke, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, in, 2, a, wkly, comp, to, win, f...","[free, entry, 2, wkly, comp, win, fa, cup, fin...","[free, entri, 2, wkli, comp, win, fa, cup, fin...","[free, entri, 2, wkli, comp, win, fa, cup, fin..."
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say so early hor u c already then say,"[u, dun, say, so, early, hor, u, c, already, t...","[u, dun, say, early, hor, u, c, already, say]","[u, dun, say, earli, hor, u, c, alreadi, say]","[u, dun, say, earli, hor, u, c, alreadi, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah i dont think he goes to usf he lives aroun...,"[nah, i, dont, think, he, goes, to, usf, he, l...","[nah, dont, think, goes, usf, lives, around, t...","[nah, dont, think, goe, usf, live, around, tho...","[nah, dont, think, goe, usf, live, around, tho..."

In [ ]:
display(df_spam[['v1', 'v2', 'lemmatized_tokens']].head())

,v1,v2,lemmatized_tokens
0,ham,"Go until jurong point, crazy.. Available only ...","[go, jurong, point, crazi, avail, bugi, n, gre..."
1,ham,Ok lar... Joking wif u oni...,"[ok, lar, joke, wif, u, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,"[free, entri, 2, wkli, comp, win, fa, cup, fin..."
3,ham,U dun say so early hor... U c already then say...,"[u, dun, say, earli, hor, u, c, alreadi, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...","[nah, dont, think, goe, usf, live, around, tho..."

In [ ]:
df_spam['clean_text'] = df_spam['lemmatized_tokens'].apply(lambda x: ' '.join(x))
display(df_spam[['v1', 'v2', 'clean_text']].head())

,v1,v2,clean_text
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,ham,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,ham,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think goe usf live around though

### Bag Of Words

In [ ]:
count_vectorizer_obj = CountVectorizer()
count_vec = count_vectorizer_obj.fit_transform(df_spam['clean_text'])
count_vec.shape

(5572, 7971)

## Classification

### Label Encoding

In [ ]:
label_encoder_model = LabelEncoder()
df_spam['v1_encoded'] = label_encoder_model.fit_transform(df_spam['v1'])

In [ ]:
X = count_vec
y = df_spam['v1_encoded']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
LinearRegression_model = LogisticRegression()
LinearRegression_model.fit(X_train, y_train)

y_pred = LinearRegression_model.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.979372197309417

Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       965
           1       1.00      0.85      0.92       150

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115


Confusion Matrix:
[[965   0]
 [ 23 127]]

### Boosting

In [ ]:
 # Initialize AdaBoostClassifier
adaboost_model = AdaBoostClassifier(random_state=42)

# Train the model
adaboost_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_adaboost = adaboost_model.predict(X_test)

# Evaluate the model
print(f"AdaBoost Accuracy: {accuracy_score(y_test, y_pred_adaboost)}")
print("\nAdaBoost Classification Report:")
print(classification_report(y_test, y_pred_adaboost))
print("\nAdaBoost Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_adaboost))

AdaBoost Accuracy: 0.9255605381165919

AdaBoost Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       965
           1       0.95      0.47      0.63       150

    accuracy                           0.93      1115
   macro avg       0.94      0.73      0.79      1115
weighted avg       0.93      0.93      0.91      1115


AdaBoost Confusion Matrix:
[[961   4]
 [ 79  71]]

## TF - IDF

In [ ]:
corpus = df_spam['clean_text'].tolist()
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri questionstd txt ratetc appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah dont think goe usf live around though',
 'freemsg hey darl 3 week word back id like fun still tb ok xxx std chg send �150 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea �900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'im gon na home soon dont want talk stuff anymor tonight k ive cri enough today',
 'six chanc win cash 100 20000 pound txt csh11 send 87575 cost 150pday 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free membership �100000 prize jackpot txt word claim 81010 tc wwwdbuknet lccltd pobox 4403ldnw1a7rw18',
 'ive search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click httpwap xxxmobilemovieclubcomnqjkgighjjgcbl',
 'oh kim watch',
 'eh u rememb 2 spell name ye v naughti make v wet',
 'fine that�� way u feel that�� way gota b',
 'england v macedonia dont miss goalsteam news txt ur nation team 87077 eg england 87077 trywal scotland 4txt̼120 poboxox36504w45wq 16',
 'serious spell name',
 'i���m go tri 2 month ha ha joke',
 '� pay first lar da stock comin',
 'aft finish lunch go str lor ard 3 smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice im realli hungri tho suck mark get worri know im sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'im back amp pack car ill let know there room',
 'ahhh work vagu rememb feel like lol',
 'wait that still clear sure sarcast that x doesnt want live u',
 'yeah got 2 v apologet n fallen actin like spoilt child got caught till 2 wont go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg �5month plea confirm repli ye repli charg',
 'yup ok go home look time msg � xuhui go learn 2nd may lesson 8am',
 'oop ill let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello how saturday go text see youd decid anyth tomo im tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 '07732584351 rodger burn msg tri call repli sm free nokia mobil free camcord plea call 08000930705 deliveri tomorrow',
 'see',
 'great hope like man well endow ltgt inch',
 'callsmessagesmiss call',
 'didnt get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler cant could mayb ask around bit',
 'u dont know stubborn didnt even want go hospit kept tell mark im weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like ltgt half eighth smarter though get almost whole second gram ltgt',
 'k fyi x ride earli tomorrow morn he crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave im sorri didnt dont give im sorri offer im sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lturlgt',
 'congrat 1 year special cinema pas 2 call 09061209465 c suprman v matrix3 starwars3 etc 4 free bx420ip45w 150pm dont miss',
 'sorri ill call later meet',
 'tell reach',
 'yesgauti sehwag odi seri',
 'gon na pick 1 burger way home cant even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom plea advis follow recent review mob award �1500 bonu prize call 09066364589',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav acoentry41 �1000 claim txt di 87121 186�150morefrmmob shracomorsglsuplt10 ls1 3aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wan na someth xx',
 'kkwhere youhow perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper ltgt',
 'still look job much ta earn',
 'sorri ill call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later dont network urgnt sm',
 'real u get yo need 2 ticket one jacket im done alreadi use multi',
 'ye start send request make pain came back im back bed doubl coin factori got ta cash nitro',
 'im realli still tonight babe',
 'ela kanoil download come wen ur free',
 'yeah don���t stand close tho you���ll catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean havent done stuff42moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum1 hurt u smile becoz someon still love see u smile',
 'plea call custom servic repres 0800 169 6031 10am9pm guarante �1000 cash �5000 prize',
 'havent plan buy later check alreadi lido got 530 show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix 85069 verifi get usher britney fml',
 'watch telugu moviewat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u ham',
 'plea dont text anymor noth el say',
 'okay name ur price long legal wen pick u ave x am xx',
 'im still look car buy gone 4the drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'wow your right didnt mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight ill hit get cash',
 'would ip address test consid comput isnt minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess he busi',
 'plural noun research',
 'go dinnermsg',
 'im ok wif co like 2 tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show �1000 prize guarante call 09064012160 claim code k52 valid 12hr 150ppm',
 'wa ur openin sentenc formal anyway im fine juz tt im eatin much n puttin weighthaha anythin special happen',
 'enter cabin pa said happi bday bos felt special askd 4 lunch lunch invit apart went',
 'winner u special select 2 receiv �1000 4 holiday flight inc speak live oper 2 claim 0871277810910pmin 18',
 'goodo ye must speak friday eggpotato ratio tortilla need',
 'hmmmi uncl inform he pay school directli pl buy food',
 'privat 2004 account statement 07742676969 show 786 unredeem bonu point claim call 08719180248 identifi code 45239 expir',
 'urgent mobil award �2000 bonu caller prize 5903 final tri contact u call landlin 09064019788 box42wr29c 150ppm',
 'new address applespairsal malarki',
 'today voda number end 7548 select receiv 350 award match plea call 08712300220 quot claim code 4041 standard rate app',
 'go sao mu today done 12',
 '�� predict wat time �ll finish buy',
 'good stuff',
 'knowyetund hasnt sent money yet sent text bother send dont involv anyth shouldnt impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'kkhow much cost',
 'im home',
 'dear call tmorrowpl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr 82277 �150 sptyron',
 'want 2 get laid tonight want real dog locat sent direct 2 ur mob join uk largest dog network bt txting gravel 69888 nt ec2a 31pmsg150p',
 'haf msn yijuehotmailcom',
 'call meet',
 'check room befor activ',
 'youll rcv msg chat svc free hardcor servic text go 69988 u get noth u must age verifi yr network tri',
 'got c lazi type forgot � lect saw pouch like v nice',
 'k text your way',
 'sir wait mail',
 'swt thought nver get tire littl thing 4 lovabl person cozsomtim littl thing occupi biggest part heart gud ni8',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class u',
 'freemsg havent repli text im randi sexi femal live local luv hear u netcollex ltd 08700621170150p per msg repli stop end',
 'ummmawil call check inour life begin qatar pl pray hard',
 'ki delet contact',
 'sindu got job birla soft',
 'wine flow im never',
 'yup thk cine better co need 2 go 2 plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show ill see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'im leav hous',
 'hello love get interview today happi good boy think mear miss',
 'custom servic annonc new year deliveri wait plea call 07046744435 arrang deliveri',
 'winner u special select 2 receiv �1000 cash 4 holiday flight inc speak live oper 2 claim 0871277810810',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parentsi new job hand',
 'im love im excit day spend make happi',
 'pl stop bootydeli 32f invit friend repli yes434 no434 see wwwsmsacubootydeli stop send stop frnd 62468',
 'bangbab ur order way u receiv servic msg 2 download ur content u goto wap bangb tv ur mobil internetservic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show �900 prize guarante call 09061701939 claim code s89 valid 12hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet formclark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go 4 free abt muz call u discus liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well im gon na finish bath goodfin night',
 'let know youv got money carlo make call',
 'u still go mall',
 'turn friend stay whole show wont back til ltgt feel free go ahead smoke ltgt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v wed like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr8 weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth greatby',
 'hello handsom find job lazi work toward get back net mummi where boytoy miss',
 'haha awesom minut',
 'plea call custom servic repres freephon 0808 145 4742 9am11pm guarante �1000 cash �5000 prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find 30th august wwwareyouuniquecouk',
 'im sorri ive join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope youv settl new school year wishin gr8 day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet 1pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc ltgt',
 'sent ltgt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr ltdecimalgt keralacircl prepaid account balanc r ltdecimalgt transact id kr ltgt',
 'goodmorn sleep ga',
 'u call alter 11 ok',
 '�� say like dat dun buy ericsson oso oredi lar',
 'enter cabin pa said happi bday bos felt special askd 4 lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'plea give u connect today ltdecimalgt refund bill',
 'shoot big load get readi',
 'what bruv hope great break reward semest',
 'home alway chat',
 'kkgoodstudi well',
 'yup � noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire havent slept well past night',
 'easi ahsen got select mean good',
 'take exam march 3',
 'yeah think use gt atm regist sure there anyway help let know sure readi',
 'ok prob take ur time',
 'o call ubandu run without instal hard diskyou use o copi import file system give repair shop',
 'sorri ill call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 '500 new mobil 2004 must go txt nokia 89545 collect todayfrom �1 www4tcbiz 2optout 08718726270150gbpmtmsg18',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career 2 flyng start 2 find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side ltgt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah im',
 'yesher tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join 4 10p repli name age eg sam 25 18 msg recdthirtyeight penc',
 'print oh ltgt come upstair',
 'ill littl closer like bu stop street',
 'youwhen wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say im alway correct',
 'u 447801259231 secret admir look 2 make contact ufind rreveal think ur specialcal 09058094597',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat im baig face watch realli like e watch u gave co fr u thanx 4 everyth dat uve done today im touch',
 'u dont rememb old commerci',
 'late said websit didnt dont slipper',
 'ask call ok',
 'kalli wont bat 2nd inning',
 'didnt work oh ok goodnight ill fix readi time wake dearli miss good night sleep',
 'congratul ur award 500 cd voucher 125gift guarante free entri 2 100 wkli draw txt music 87066 tnc wwwldewcom1win150ppmx3age16',
 'ranjith cal drpd deeraj deepak 5min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 'doinghow',
 'up 3day also ship compani take 2wk way usp take week get lag may bribe nipost get stuff',
 'im back lem know your readi',
 'dont necessarili expect done get back though im headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset 750 anytim network min unlimit text camcord repli call 08000930705',
 'i���m park next mini come today think',
 'yup',
 'anyway im go shop co si done yet dun disturb u liao',
 'luton 0125698789 ring ur around h',
 'hey realli horni want chat see nake text hot 69698 text charg 150pm unsubscrib text stop 69698',
 'dint come u',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang 25 free credit go club4mobilescom choos content stop txt club stop 87070 150pwk club4 po box1146 mk45 2wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special 500 pound genuin hmv voucher answer 4 easi question play send hmv 86688 infowww100percentrealcom',
 'usf guess might well take 1 car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom ill see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pas last night get ahold anybodi let know ill throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u 2 give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dearshal mail tonitebusi streetshal updat toniteth look okvarunnathu edukkukaye raksha ollubut good one real sen',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop 4 got bit',
 'much buzi',
 'accident delet messag resend plea',
 'tmobil custom may claim free camera phone upgrad pay go sim card loyalti call 0845 021 3680offer end 28thfebtc appli',
 'unless situat go gurl would appropri',
 'hurt tea make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomoc believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date 4u rodds1 21m aberdeen unit kingdom check httpimg sm acwicmb3cktz8r74 blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u wont buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap 82468',
 'garag key arent bookshelf',
 'today accept dayu accept brother sister lover dear1 best1 clos1 lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win �200 week weekli quiz text play 85222 nowtc winnersclub po box 84 m26 3uz 16 gbp150week',
 'say hell give call friend got money he definit buy end week',
 'hi way u 2day normal waythi real ur uniquei hope know u 4 rest mylif hope u find wot lost',
 'made day great day',
 'kkadvanc happi pongal',
 'hmmm guess go 4 kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend im afraid',
 'decemb mobil 11mth entitl updat latest colour camera mobil free call mobil updat co free 08002986906',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l8 co 2 buse hav gon past co full im still waitin 4 1 pete x',
 'would great well guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'callsmessagesmiss call',
 'hi dahow today class',
 'id say that good sign well know track record read woman',
 'cool text your park',
 'im read text sent meant joke read light',
 'kkapo kgood movi',
 'mayb could get book tomo return immedi someth',
 'call germani 1 penc per minut call fix line via access number 0844 861 85 85 prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool plea contact report supervisor',
 'valentin day special win �1000 quiz take partner trip lifetim send go 83600 150pmsg rcvd custcare08718720201',
 'tadaaaaa home babe still',
 'cool come havent wine dine',
 'sleepingand surf',
 'sorri ill call later',
 'u call right call hand phone',
 'ok that great thanx lot',
 'take post come must 1000 text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnitetcpractic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag dointerest sextextukcom txt xxuk suzi 69876 txt cost 150 per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah cant help ive never iphon',
 'your car hour half im go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault im basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'ltgt ish minut 5 minut ago wtf',
 'thank callingforgot say happi onam sirjii fine rememb met insur personmeet qatar insha allahrakhesh ex tata aig join tisscotays',

In [ ]:
TF_IDF_vectorizer = TfidfVectorizer()
tf_idf_vector = TF_IDF_vectorizer.fit_transform(corpus)
tf_idf_vector.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
TF_IDF_vectorizer.get_feature_names_out()

array(['008704050406', '0089mi', '0121', ..., 'zoom', 'zouk', 'zyada'],
      dtype=object)

## N-grams

In [ ]:
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
# n_gram range parameter set to make sure we are getting bigrams only
bigram_vectors = bigram_vectorizer.fit_transform(corpus)
bigram_vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
bigram_vectorizer.get_feature_names_out()

array(['008704050406 sp', '0089mi last', '0121 2025050', ..., 'zoom cine',
       'zouk nichol', 'zyada kisi'], dtype=object)

## Word to Vector

In [ ]:
api.info()['models'].keys() # word2 Vec model avaliabble in gensim library

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])

In [ ]:
# loading word2vec-google-news-300 model
word2vecmodel = api.load('word2vec-google-news-300')
print('model loading successful')

[==================================================] 100.0% 1662.8/1662.8MB downloaded
model loading successful

In [ ]:
word2vecmodel['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [ ]:
# testing words in the model
word2vecmodel['Queen']

array([-0.22070312, -0.17480469, -0.10498047,  0.2578125 ,  0.16210938,
       -0.13085938, -0.16699219,  0.07373047, -0.07226562,  0.02404785,
       -0.13964844,  0.02197266,  0.17675781, -0.19140625,  0.0378418 ,
       -0.01782227, -0.03710938, -0.03735352,  0.15625   ,  0.08837891,
        0.0534668 , -0.02392578, -0.2734375 , -0.2578125 , -0.00720215,
        0.06933594, -0.21777344, -0.10058594,  0.2421875 ,  0.03417969,
       -0.12890625, -0.1171875 , -0.18261719,  0.04321289, -0.125     ,
       -0.09960938,  0.26367188,  0.375     , -0.32421875, -0.1328125 ,
       -0.13378906, -0.50390625, -0.05908203,  0.04077148,  0.23730469,
       -0.03393555, -0.01495361, -0.09765625, -0.06445312,  0.02087402,
       -0.10302734,  0.10449219,  0.20019531, -0.16503906, -0.01196289,
        0.30859375, -0.41015625, -0.22070312,  0.08056641, -0.12792969,
        0.13085938,  0.28515625, -0.07275391,  0.02612305,  0.01916504,
       -0.16992188,  0.01745605,  0.13085938, -0.17089844, -0.10107422,
        0.10791016,  0.0035553 ,  0.0300293 , -0.12792969,  0.17285156,
       -0.06079102,  0.02990723,  0.08544922,  0.22363281, -0.03344727,
       -0.28125   , -0.02307129,  0.0559082 , -0.3125    , -0.0098877 ,
       -0.01306152, -0.37695312,  0.10253906,  0.20605469,  0.12890625,
       -0.09960938, -0.06494141,  0.01446533, -0.09375   ,  0.15234375,
        0.21777344,  0.17871094,  0.02783203, -0.0390625 ,  0.10986328,
       -0.12158203, -0.18945312,  0.01867676, -0.13476562, -0.16992188,
       -0.15234375, -0.33789062, -0.13183594,  0.08935547, -0.14355469,
        0.06738281,  0.29882812,  0.24316406,  0.078125  ,  0.30859375,
       -0.08789062,  0.16015625, -0.4140625 ,  0.3046875 ,  0.15722656,
       -0.01275635, -0.03735352,  0.08496094, -0.3359375 , -0.06640625,
       -0.04492188, -0.25390625,  0.01293945, -0.14160156,  0.02941895,
        0.09179688,  0.2265625 , -0.25195312,  0.01416016,  0.21875   ,
        0.16796875, -0.1015625 , -0.05395508, -0.09912109, -0.14160156,
       -0.01519775, -0.02954102,  0.08154297, -0.1796875 ,  0.32226562,
        0.03686523, -0.02050781, -0.07519531, -0.08642578, -0.08740234,
       -0.01428223, -0.05126953,  0.16699219, -0.10498047, -0.05834961,
       -0.08837891, -0.00376892, -0.00300598,  0.1875    , -0.25      ,
        0.0390625 ,  0.12597656,  0.30859375, -0.00805664, -0.10791016,
       -0.08740234, -0.26953125, -0.3984375 , -0.02978516,  0.04003906,
       -0.07421875,  0.16601562,  0.22851562,  0.1796875 , -0.16894531,
       -0.06445312, -0.07958984,  0.04663086, -0.11865234, -0.17382812,
       -0.11572266, -0.10009766,  0.10107422, -0.203125  , -0.08105469,
       -0.04638672,  0.375     ,  0.24902344, -0.16210938,  0.08105469,
       -0.35742188,  0.07226562,  0.07080078, -0.00193024, -0.16601562,
        0.19140625,  0.34179688,  0.05102539,  0.08300781, -0.07128906,
        0.03149414, -0.11523438, -0.06054688,  0.05053711,  0.04345703,
       -0.10986328,  0.05834961,  0.43945312,  0.10009766,  0.17480469,
        0.0324707 ,  0.13378906,  0.11914062, -0.17675781, -0.07568359,
       -0.25      , -0.17578125, -0.25585938,  0.13574219,  0.08789062,
        0.16308594, -0.00488281,  0.33203125, -0.26171875, -0.08203125,
        0.06225586, -0.08398438, -0.06445312,  0.18359375,  0.10595703,
       -0.22558594, -0.1328125 , -0.39257812, -0.05908203,  0.07666016,
       -0.06494141,  0.02575684, -0.07226562,  0.20800781, -0.06298828,
        0.11572266,  0.10644531,  0.09912109, -0.25      ,  0.02172852,
        0.0612793 , -0.16503906,  0.01965332, -0.00946045, -0.2578125 ,
        0.02160645, -0.01147461,  0.17773438,  0.33398438,  0.01300049,
        0.17675781, -0.31054688,  0.02282715, -0.1875    , -0.13574219,
        0.25      ,  0.33984375, -0.15722656, -0.06591797, -0.0378418 ,
       -0.09716797, -0.39648438,  0.13085938,  0.03344727,  0.046875  ,
       -0.14355469,  0.21777344,  0.22070312,  0.20019531,  0.45507812,
       -0.40820312,  0.11767578, -0.09765625, -0.05957031,  0.27929688,
        0.125     , -0.3203125 ,  0.17773438,  0.00527954,  0.24902344,
       -0.05712891,  0.00637817,  0.00408936, -0.12988281,  0.16894531,
        0.05615234, -0.16113281, -0.28515625, -0.06103516, -0.03369141,
        0.02600098,  0.03491211, -0.13769531,  0.12060547, -0.09375   ],
      dtype=float32)

In [ ]:
# find cosine similarity
similarity = word2vecmodel.similarity('king', 'queen')
similarity

np.float32(0.6510957)

In [ ]:
# find cosine similarity
similarity = word2vecmodel.similarity('woman', 'man')
similarity

np.float32(0.76640123)

In [ ]:
word2vecmodel.most_similar('king', topn= 10)

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

## Continuous Bag of Words

In [ ]:
corpus_1 = ["King and Queen rule the kingdom",
            "The man is walking in the park",
            "The woman is cooking food in the kitchen",
            "The child is playing with toys",
            "Computer and laptop are electronic devices",
            "Python and Java are popular programming languages"]

In [ ]:
# tokenize the entire corpus

In [ ]:
tokenized_corpus = [word_tokenize(document.lower()) for document in corpus_1]
tokenized_corpus

[['king', 'and', 'queen', 'rule', 'the', 'kingdom'],
 ['the', 'man', 'is', 'walking', 'in', 'the', 'park'],
 ['the', 'woman', 'is', 'cooking', 'food', 'in', 'the', 'kitchen'],
 ['the', 'child', 'is', 'playing', 'with', 'toys'],
 ['computer', 'and', 'laptop', 'are', 'electronic', 'devices'],
 ['python', 'and', 'java', 'are', 'popular', 'programming', 'languages']]

In [ ]:
# building CBoW neural network
model_cbow = Word2Vec(sentences = tokenized_corpus,
                      vector_size = 50, # word embedding size
                      window = 5,  # context information window
                      epochs = 20,
                      min_count = 1 # ignore words with frequency < 1
                      )

In [ ]:
model_cbow.wv.most_similar('king', topn= 3)

[('programming', 0.2684629261493683),
 ('python', 0.2641042470932007),
 ('is', 0.22139960527420044)]